# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-06 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='blogsubscriber',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='blogsubscriber',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userpostwatched',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='userpostwatched',
            old_name='user_id',
            new_name='user',
        ),
    ]
