# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-06 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_auto_20180306_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_id',
            new_name='blog',
        ),
    ]
